// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anocscgvdkvbggxflulv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFub2NzY2d2ZGt2YmdneGZsdWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTg0MjcsImV4cCI6MjA1NTUzNDQyN30.SbbN3GBrlz6w6A50Lju_74uqcKkv69OfY7mW_4NmQfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);